"""Core domain models and ports for LinguaLoop."""

from lingualoop.core.domain import (
    CapabilityRequirement,
    CorrectionIntensity,
    FeedbackItem,
    FeedbackType,
    LanguageEnum,
    LearningMaterial,
    MaterialAnalysis,
    MaterialExpression,
    MaterialSourceType,
    Message,
    MessageRole,
    PatternManifest,
    PluginManifest,
    PracticeInstruction,
    PracticePlan,
    PracticeSession,
    ProficiencyLevel,
    ReviewItem,
    ReviewItemKind,
    SessionEvent,
    SessionEventType,
    SessionStatus,
    UserProfile,
)
from lingualoop.core.ports import EventStore, LearningLLMProvider

__all__ = [
    "CapabilityRequirement",
    "CorrectionIntensity",
    "EventStore",
    "FeedbackItem",
    "FeedbackType",
    "LanguageEnum",
    "LearningLLMProvider",
    "LearningMaterial",
    "MaterialAnalysis",
    "MaterialExpression",
    "MaterialSourceType",
    "Message",
    "MessageRole",
    "PatternManifest",
    "PluginManifest",
    "PracticeInstruction",
    "PracticePlan",
    "PracticeSession",
    "ProficiencyLevel",
    "ReviewItem",
    "ReviewItemKind",
    "SessionEvent",
    "SessionEventType",
    "SessionStatus",
    "UserProfile",
]
